# ===========================
#  CONFIGURACIÓN DEL SERVIDOR
# ===========================
server.port=${PORT:8080}
spring.application.name=cruz_ozzy

# ===========================
#  CONFIGURACIÓN DE BASE DE DATOS
# ===========================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ===========================
#  CONFIGURACIÓN DE CORREO (SMTP)
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:sabormasterclass@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:rvlc cqoi mbxp muzy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
